### ISSUE TITLE
[Homework4] Fix modules alg_1913.py & alg_1910_main.py

### ISSUE THREAD

**Issue by johnklee** [johnklee/oo_dp_lesson#5]
在這個 Homework 中在執行 <a href='https://github.com/johnklee/oo_dp_lesson/blob/master/homework04/alg_1913.py'><font color='olive'>alg_1913.py</font></a> 會發生例外:
```console
# ./alg_1913.py
Traceback (most recent call last):
  File "./alg_1913.py", line 22, in <module>
    rel = sol.maxProductDifference(nums)
  File "./alg_1913.py", line 10, in maxProductDifference
    return sorted_nums[0] * sorted_nums[1] - sorted_nums[-1] * sorted_nums[-2]
IndexError: list index out of range
```

在執行 <a href='https://github.com/johnklee/oo_dp_lesson/blob/master/homework04/alg_1910_main.py'><font color='olive'># ./alg_1910_main.py</font></a> 會 hang 住:
```console
# ./alg_1910_main.py
```

這裡需要你透過 PDB 進行 debugging 並修復他們. 加油!

**Comment by johnklee** [comment]
Confirmed the issue is fixed in below PR. Good job:
https://github.com/johnklee/oo_dp_lesson/pull/8/files

Closed this issue as well.
